services:
  frontend:
    build:
      context: ./frontend
    image: module_marketplace/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    image: module_marketplace/backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  electron:
    build: 
      context: ./electron-app
    image: module_marketplace/electron:latest
    depends_on:
      - frontend
    ports:
      - "4000:4000"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
