services:
  frontend:
    build:
      context: ./frontend
    image: module_marketplace/frontend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    image: module_marketplace/backend:latest
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/MM_Data
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # Korrigiert auf /data/db, nicht /src/data/


  electron:
    build: 
      context: ./electron-app
    image: module_marketplace/electron:latest
    depends_on:
      - frontend
    ports:
      - "4000:4000"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix


volumes:
  mongodb_data:  # Diese Zeile definiert das Volumen