name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker-compose.yml
          push: false # Set to false if you don't want to push the image
          tags: your-image-name:latest # Ersetze dies durch deinen gewünschten Tag

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d
