name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install and build frontend
    - name: Install dependencies for frontend
      run: npm ci
      working-directory: ./frontend

    - name: Build frontend
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Test frontend
      run: npm test
      working-directory: ./frontend

    # Install and build backend
    - name: Install dependencies for backend
      run: npm ci
      working-directory: ./backend

    - name: Build backend
      run: npm run build --if-present
      working-directory: ./backend

    - name: Test backend
      run: npm test
      working-directory: ./backend

    # Install and build electron-app
    - name: Install dependencies for electron-app
      run: npm ci
      working-directory: ./electron-app

    - name: Build electron-app
      run: npm run build --if-present
      working-directory: ./electron-app

    - name: Test electron-app
      run: npm test
      working-directory: ./electron-app
